spring:
  application:
    name: discovery-sever
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123

---
spring:
  profiles: peer1
server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  instance:
      hostname: localhost
      preferIpAddress: true
      metadata-map:
        instanceId: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  server:
    enable-self-preservation: false
  environment: dev     #${spring.profiles.active}
  datacenter: hangzhou

---
spring:
  profiles: peer2
server:
  port: 8762                    # 指定该Eureka实例的端口
eureka:
  instance:
      hostname: localhost
      preferIpAddress: true
      metadata-map:
        instanceId: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false
  environment: dev     #${spring.profiles.active}
  datacenter: hangzhou


# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756