server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: http://git.oschina.net/taska/spring-cloud-config-repo
          search-paths: foo,bar*
          username: fooololo@gmail.com
          password:
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG


# 测试：访问http://localhost:8080/application/default